<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>FullSpectrum.Knowledge.TestHost</RootNamespace>
    <AssemblyName>FullSpectrum.Knowledge.TestHost</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FullSpectrum.Knowledge.Contracts/FullSpectrum.Knowledge.Contracts.csproj" />
  </ItemGroup>
</Project>
